---
tenants:
  BLUE:
    redist_hostroutes: true
    route_target: '20'
    vlan_vni_base: '20000'
    vlans:
      '20': {host_route_export: true, ip: 10.20.20.1, mask: '24', name: BLUE_WEB,
        vlan_l3: true}
      '21': {host_route_export: true, ip: 10.20.21.1, mask: '24', name: BLUE_APP,
        vlan_l3: true}
    vrf_vni_base: '50002'
  RED:
    redist_hostroutes: true
    route_target: '10'
    vlan_vni_base: '10000'
    vlans:
      '10': {host_route_export: true, ip: 10.10.10.1, mask: '24', name: RED_WEB, vlan_l3: true}
      '11': {host_route_export: true, ip: 10.10.11.1, mask: '24', name: RED_APP, vlan_l3: true}
    vrf_vni_base: '50001'
